let data = {
  warzywa: [
    "marchew",
    "ziemniaki",
    "por",
    "seler",
    "kalafior",
    "kapusta",
    "bataty",
    "bakłazan",
    "cukinia",
    "pomidor",
    "ogorek",
  ],
  owoce: ["banany", "truskawki", "jablka", "czeresne", "pomarancze"],
  sosy: ["sos czosnkowy", "ketchup", "majonez"],
  konserwy: ["ryba w puszce", "korniszone"],
  pszyprawy: [
    "sol",
    "pieprz",
    "curry",
    "papryka slodka",
    "papryka ostra",
    "sol ziolowa",
    "ziola prowansalskie",
  ],
  mrozone: [
    "pierogi",
    "warzywa mrozone",
    "zapiekanki",
    "pizza mrozona",
    "paluszki rybne",
  ],
  mieso: ["piers z kurczaka", "udka z kurczaka", "jakas szynka"],
  nabial: [
    "mleko",
    "maslo",
    "smarowidlo",
    "jogurt",
    "ser zwykly",
    "ser mozarella",
    "twarog",
    "serek wiejski",
    "serek wloski",
    "ser cheddar",
    "ser grana padano",
  ],
  przekaski: ["chipsy", "chrupki", "krakersy", "orzeszki"],

  slodycze: [
    "czekolada mleczna",
    "czekolada biala",
    "czekolada ciemna",
    "czekolada bakaliowa",
    "czekolada jakas ekstra",
    "grzeski toffi",
    "grzeski suche",
    "grzeski mleczne",
    "princessa kokosowa",
    "kinder jajko",
    "rurki z kremem",
    "ciastka",
  ],
  pickosoft: ["karotka", "sok duzy", "cola"],
  chemia: [
    "pasta do zębów",
    "płyn do naczyń",
    "papier toaletowy",
    "plyn do plukania zebow",
    "plyn do mycia kibla",
    "plyn do podlog",
    "spray do kurzy",
  ],
  alkohol: ["piwo", "wino"],
};
